import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "The Music Store",
  icons: {
    icon: "./next.svg",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1>Navbar</h1>
        {children}
      </body>
    </html>
  );
}
